/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.bookmanagement.form;

import com.softech.bookmanagement.helpers.DataValidator;
import com.softech.bookmanagement.helpers.DatabaseHelper;
import com.softech.bookmanagement.helpers.MessageDialogHelper;
import com.softech.bookmanagement.model.Book;
import com.softech.bookmanagement.model.BookDAO;
import com.softech.bookmanagement.model.Employee;
import com.softech.bookmanagement.model.EmployeeDAO;
import com.softech.bookmanagement.model.InvoiceDTO;
import com.softech.bookmanagement.model.Order;
import com.softech.bookmanagement.model.OrderDAO;
import com.softech.bookmanagement.model.OrderDetail;
import com.softech.bookmanagement.model.OrderDetailDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Nguyen Bae
 */
public class Form_Invoice extends javax.swing.JPanel {
    DefaultTableModel tblModel,tblModel2;
     private JFrame mainFrame;
    /**
     * Creates new form Form_Invoice
     */
    ArrayList<InvoiceDTO> listInvoice = new ArrayList<InvoiceDTO>(); 
    public Form_Invoice() {
        initComponents();
        initTable();
        loadNameEmployees();
        loadNameBooks();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void initTable (){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"OrderId","CreateDate","UserID"});
        tblBook.setModel(tblModel); 
    }
    private void loadTable(){
        try{
            OrderDAO dao = new OrderDAO();
            List<Order> list = dao.findAll();
            tblModel.setRowCount(0);
            for(Order em:list){
                tblModel.addRow(new Object[]{
                    em.getOrderId(),em.getCreateDate(),em.getUserID()
                });
            }
            tblModel.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "error");
        }
    }
    private void loadNameEmployees(){
        String sql = "Select FullName from [User]";
        cbEmployees.removeAllItems();
        try{
        PreparedStatement pstmt = DatabaseHelper.connectSQLServer().prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        cbEmployees.removeAllItems();
            while (rs.next()) {
                cbEmployees.addItem(rs.getString("FullName")); 
            }
            rs.close();
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }
     private void loadNameBooks(){
       String sql = "Select [Title] from [Book]";
        cbBook.removeAllItems();
        try{
        PreparedStatement pstmt = DatabaseHelper.connectSQLServer().prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        cbBook.removeAllItems();
            while (rs.next()) {
                cbBook.addItem(rs.getString("Title")); 
            }
            rs.close();
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        txtOrderId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbBook = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbEmployees = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        panelBorder1 = new com.softech.bookmanagement.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable1 = new javax.swing.JScrollPane();
        tblBook = new com.softech.bookmanagement.swing.Table();
        panel2 = new javax.swing.JLayeredPane();
        btnAddbook = new javax.swing.JButton();
        panel3 = new javax.swing.JLayeredPane();
        spTable = new javax.swing.JScrollPane();
        tblBook12 = new com.softech.bookmanagement.swing.Table();
        btnCreateOrder = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(919, 620));

        txtOrderId.setBackground(new java.awt.Color(242, 242, 242));
        txtOrderId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOrderId.setToolTipText("");
        txtOrderId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 43, 150));
        jLabel3.setText("Employees");

        cbBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(63, 43, 150));
        jLabel10.setText("OrderId");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(63, 43, 150));
        jLabel11.setText("Book");

        cbEmployees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(63, 43, 150));
        jLabel12.setText("Quantity");

        txtQuantity.setBackground(new java.awt.Color(242, 242, 242));
        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuantity.setToolTipText("");
        txtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        panel.setLayer(txtOrderId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(cbBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(cbEmployees, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(txtQuantity, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderId)
                    .addComponent(cbBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEmployees, javax.swing.GroupLayout.Alignment.TRAILING, 0, 254, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Invoice Management");

        tblBook.setBackground(new java.awt.Color(242, 242, 242));
        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "CreateDate", "UserID"
            }
        ));
        tblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookMouseClicked(evt);
            }
        });
        spTable1.setViewportView(tblBook);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(684, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(spTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBorder1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(spTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        btnAddbook.setBackground(new java.awt.Color(63, 43, 150));
        btnAddbook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddbook.setForeground(new java.awt.Color(255, 255, 255));
        btnAddbook.setText("   ADD");
        btnAddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddbookActionPerformed(evt);
            }
        });

        panel2.setLayer(btnAddbook, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddbook, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddbook, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBook12.setBackground(new java.awt.Color(242, 242, 242));
        tblBook12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "CreateDate", "UserID"
            }
        ));
        spTable.setViewportView(tblBook12);

        btnCreateOrder.setBackground(new java.awt.Color(63, 43, 150));
        btnCreateOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateOrder.setText("Create");
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(63, 43, 150));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        panel3.setLayer(spTable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(btnCreateOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents
       private void setFieldEmpty(){
        txtOrderId.setText("");
        
    }    Form_OrderDetail orderdetail = new Form_OrderDetail();
    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        String idUser = "1";
        if(sb.length() > 0){
            MessageDialogHelper.showErrorDialog(mainFrame, sb.toString(),"ERROR");
            return ;
        }
        try{
            EmployeeDAO empDao = new EmployeeDAO();
            BookDAO bookdao = new BookDAO();
            OrderDetailDAO orderDetailDAO = new OrderDetailDAO();
            List<Employee> listuser = empDao.findAll();
            for(Employee employee:listuser){
                if(employee.getFullName().equals(cbEmployees.getSelectedItem().toString())){
                    idUser = employee.getUserID();
                }
            }
            
            Order order = new Order();
            long millis = System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            order.setOrderId(txtOrderId.getText());
            order.setCreateDate(date);
            order.setNameUser(cbEmployees.getSelectedItem().toString());
            order.setUserID(idUser);
            OrderDAO orderDao = new OrderDAO();
            
            
            orderDao.findAll();
            if(orderDao.insert(order)){
                
                for(InvoiceDTO invoice:listInvoice){
                    Book book = bookdao.findBookByName(invoice.getNameBook());
                    OrderDetail orderdetail = new OrderDetail();
                    orderdetail.setOrderID(txtOrderId.getText());
                    orderdetail.setBookID(book.getISBN());
                    orderdetail.setPrice((float)book.getPrice());
                    orderdetail.setNameBook(book.getTitle());
                    orderdetail.setQuantity(Integer.parseInt(invoice.getQuantity()));
                    orderDetailDAO.insert(orderdetail);
     
                }
                
                
                
                MessageDialogHelper.showMessageDialog(mainFrame,"order is saved in database", "notification");
            }else{
                MessageDialogHelper.showConfirmDialog(mainFrame, "order is save failed", "notification");
            }
            
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(mainFrame,e.getMessage(), "error");
        }
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void tblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookMouseClicked
        // TODO add your handling code here:
        int index = tblBook.getSelectedRow();
        TableModel model = tblBook.getModel();
        float PriceTotal = 0;
        orderdetail.setVisible(true);
        orderdetail.pack();
        orderdetail.setLocationRelativeTo(null);
        orderdetail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
         try
        {
            String sql = "select * from OrderDetail where OrderID = ?";
            String sql1 = "Select * from [Order] where OrderID = ?";
            PreparedStatement pstmt1 =  DatabaseHelper.connectSQLServer().prepareStatement(sql);
            pstmt1.setString(1, model.getValueAt(index,0).toString());
            ResultSet rs1 = pstmt1.executeQuery();
            OrderDetailDAO orderdetail1 = new OrderDetailDAO();
            List<OrderDetail> listorderdetail = orderdetail1.findAll("5");
            for(OrderDetail employee:listorderdetail){
               PriceTotal += employee.getPrice() * employee.getQuantity();
            }
            PreparedStatement pstmt2 =  DatabaseHelper.connectSQLServer().prepareStatement(sql1);
            pstmt2.setString(1, model.getValueAt(index,0).toString());
            ResultSet rs2 = pstmt2.executeQuery();
            if (rs1.next() && rs2.next()) {
                System.out.println(rs2.getString("NameUser"));
                orderdetail.txtOrderDetailId.setText(rs1.getString("OrderID"));
                orderdetail.txtName.setText(rs2.getString("NameUser"));
                orderdetail.txtTotal.setText(String.valueOf(PriceTotal));
                orderdetail.test = 123;
                System.out.println(orderdetail.test + "sau khi test");
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tblBookMouseClicked

    private void btnAddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddbookActionPerformed
        // TODO add your handling code here:
        
        InvoiceDTO invoice = new InvoiceDTO(
        txtOrderId.getText(), txtQuantity.getText(),
        cbBook.getSelectedItem().toString(),
        cbEmployees.getSelectedItem().toString());
        listInvoice.add(invoice);
        loadTableBook();
        
        
        
        
        
    }//GEN-LAST:event_btnAddbookActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void loadTableBook(){
        tblModel2 = (DefaultTableModel)tblBook12.getModel();
        try{
            tblModel2.setRowCount(0);
            for(InvoiceDTO em:listInvoice){
                tblModel2.addRow(new Object[]{
                    em.getNameBook(),em.getQuantity()
                });
            }
            tblModel2.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(mainFrame, e.getMessage(), "error");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddbook;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cbBook;
    private javax.swing.JComboBox<String> cbEmployees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane panel;
    private javax.swing.JLayeredPane panel2;
    private javax.swing.JLayeredPane panel3;
    private com.softech.bookmanagement.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable1;
    private com.softech.bookmanagement.swing.Table tblBook;
    private com.softech.bookmanagement.swing.Table tblBook12;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
